export const SET_USER_NAME = 'SET_USER_NAME'
export const REMOVE_USER_NAME = 'REMOVE_USER_NAME'
export const SET_OFFLINE = 'SET_OFFLINE'
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST'
export const SET_CURRENT_PLAYING = 'SET_CURRENT_PLAYING'
export const SET_MUSIC_DURATION = 'SET_MUSIC_DURATION'
export const SET_CURRENT_NAV = 'SET_CURRENT_NAV'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'


export const LODING_PLAYLISTS = 'LODING_PLAYLISTS'
export const SET_PLAYLISTS = 'SET_PLAYLISTS'
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST'
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const ADD_MUSIC_TO_PLAYLIST = 'ADD_MUSIC_TO_PLAYLIST'
export const DELETE_MUSIC_FROM_PLAYLIST = 'DELETE_MUSIC_FROM_PLAYLIST'

export const SET_COMMON_LISTS = 'SET_COMMON_LISTS'
export const SET_SEARCH_LIST = 'SET_SEARCH_LIST'


export const STOP_LOADING_MUSIC = 'STOP_LOADING_MUSIC'
export const LOADING_MUSIC = 'LOADING_MUSIC'
export const LOADING_UI = 'LOADING_UI'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'

export const SET_MUSIC_INFO = 'SET_MUSIC_INFO'
export const SET_USER_INFO = 'SET_USER_INFO'